name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  install_and_codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn schema:codegen
      - run: zip -r -q node_modules.zip node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_and_codegen_artifacts
          path: |
            .
            !node_modules/**/*
  build:
    needs: install_and_codegen
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_and_codegen_artifacts

      - name: Build
        run: |
          unzip -q node_modules.zip
          ls -al
          yarn build
  test:
    needs: install_and_codegen
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_and_codegen_artifacts

      - name: Test
        run: |
          unzip -q node_modules.zip
          ls -al
          yarn test:coverage

      # jobs:

#   build-and-test-api:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#       - run: yarn install
#       - run: yarn schema:codegen
#       - run: yarn build
#       - run: yarn test

# build:
#   needs: install
#     - run: yarn build
