name: CI

on:
  push:
    branches-ignore:
      - master

# jobs:
#   build-and-test-api:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#       - run: yarn install
#       - run: yarn schema:codegen
#       - run: yarn build
#       - run: yarn test
jobs:
  install_and_codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn schema:codegen
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: build_and_codegen_artifacts
          path: .
  build:
    needs: install_and_codegen
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: build_and_codegen_artifacts
      # - uses: actions/checkout@v2
      # - name: Use Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'
      - run: yarn build

  # build:
  #   needs: install
  #     - run: yarn build
