name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "TEST"