name: Dev Deploy

# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'     
#         required: true
#         default: 'warning'
#       tags:
#         description: 'Test scenario tags'  

# on:
#   push:
#     branches-ignore:
#       - master
on:
  workflow_dispatch

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Test"
